// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj4Q4JlnQOuUV4orMbcfrqcbsnxUxPXNI',
    appId: '1:294535765390:android:161cf8661430603f5718df',
    messagingSenderId: '294535765390',
    projectId: 'ticked-4168d',
    databaseURL: 'https://ticked-4168d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ticked-4168d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClMF7ihKQT5I5srO8svDyg93ttdDhbX44',
    appId: '1:294535765390:ios:7a0901431a5691405718df',
    messagingSenderId: '294535765390',
    projectId: 'ticked-4168d',
    databaseURL: 'https://ticked-4168d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ticked-4168d.appspot.com',
    iosClientId: '294535765390-99mc1s09elrh4igk5t1d4g10bab59qv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.biletuygulama',
  );
}
