// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf5if9QJemPg3_mKhyqQXuR-rIMg7c6Tg',
    appId: '1:730913741901:web:43c24f16709c3f9cd41004',
    messagingSenderId: '730913741901',
    projectId: 'narveri-f6587',
    authDomain: 'narveri-f6587.firebaseapp.com',
    storageBucket: 'narveri-f6587.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV06tvN8LxNA-8mk-n3oy3Vhketvj-Aks',
    appId: '1:730913741901:android:146392f016ac6439d41004',
    messagingSenderId: '730913741901',
    projectId: 'narveri-f6587',
    storageBucket: 'narveri-f6587.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNROfSV_tbkIlUok8HKA2VCGWXifvHwvk',
    appId: '1:730913741901:ios:67aee12879095447d41004',
    messagingSenderId: '730913741901',
    projectId: 'narveri-f6587',
    storageBucket: 'narveri-f6587.appspot.com',
    iosClientId: '730913741901-887c50cmor0fs5uatkt4aq2amdhittij.apps.googleusercontent.com',
    iosBundleId: 'com.example.biletuygulama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNROfSV_tbkIlUok8HKA2VCGWXifvHwvk',
    appId: '1:730913741901:ios:67aee12879095447d41004',
    messagingSenderId: '730913741901',
    projectId: 'narveri-f6587',
    storageBucket: 'narveri-f6587.appspot.com',
    iosClientId: '730913741901-887c50cmor0fs5uatkt4aq2amdhittij.apps.googleusercontent.com',
    iosBundleId: 'com.example.biletuygulama',
  );
}
